# Generated by Django 3.0.2 on 2020-10-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModels',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('category', models.CharField(default='Mobile', max_length=100)),
            ],
        ),
    ]
